i created the component for the user icon
cezarmocanu/rhi-vision pull request #28
Opened 2023-10-24 19:11 UTC by AndreeaMereu

2023-10-24 19:40 UTC, CezarMocanu-aily requested changes

2023-10-24 19:40 UTC, CezarMocanu-aily commented on src/components/atoms/SampleAtom/UserIcon.css
> +.user-border {
The file should be called Component.`module.css` instead of `.css`

2023-10-24 19:40 UTC, CezarMocanu-aily commented on src/components/atoms/SampleAtom/UserIcon.jsx
> +    return <div className="user-icon user-border grad-text">
Please add the classes using the CSS object. Check SampleAtom for an example

2023-10-24 19:40 UTC, CezarMocanu-aily commented on src/components/atoms/SampleAtom/UserIcon.jsx
> +const UserIcon = ({ userName }) => {
The prop should be called `user` not `userName` because the received object is a `user`

2023-10-24 19:40 UTC, CezarMocanu-aily commented on src/components/atoms/SampleAtom/UserIcon.jsx
> +import { useState } from 'react';
Please remove `useState` from the imports if it's not used in the component

2023-10-24 19:40 UTC, CezarMocanu-aily commented on src/components/atoms/SampleAtom/UserIcon.jsx
> +    const lastLetterLastName = lastName[0];
A shorter alternative would be to directly create a variable with both of the initial letters

```js
const nameInitials = firstName[0] + lastName[0];
```

or better, try using a string template to concatenate the text

```js
const nameInitials = `${firstName[0]}${lastName[0]}`;
```

2023-10-24 19:40 UTC, CezarMocanu-aily commented on src/components/atoms/SampleAtom/UserIcon.css
> +    background: linear-gradient(180deg, #9719D2 26.56%, rgba(255, 193, 7, 0.78) 100%);
Please use the hex code from the design for both of the colors
9719D2 - purple
FFC107 - yellow (no need for transparency)

2023-10-24 19:40 UTC, CezarMocanu-aily commented on src/components/atoms/SampleAtom/UserIcon.jsx
> +        {firstLetterFirstName}
The letters of the text should be surrounded by a `span` tag as span is used for icon or informative texts

2023-10-24 19:40 UTC, CezarMocanu-aily commented on src/components/atoms/SampleAtom/UserIcon.css
> +    width: 58.03px;
width, height, top, left don't add any benefit to the styling related to the text. Width and height should be applied on the container of the text

2023-10-24 19:40 UTC, CezarMocanu-aily commented on src/components/atoms/SampleAtom/UserIcon.css
> +    top: 715.11px;
top and left have no value here as they are only available in position defined containers, and this is none. 
In case you want to surround the text with some spacing in the container try `padding`

2023-10-24 19:40 UTC, CezarMocanu-aily commented on src/components/atoms/SampleAtom/UserIcon.css
> +    background: #1E1E1E;
background colors should be defined using the `background-color` rule

2023-10-24 19:40 UTC, CezarMocanu-aily commented on src/components/atoms/SampleAtom/UserIcon.css
> +.user-border {
Please add the file inside the dedicated folder for this atom. Right now it's inside SampleAtom but should be inside UserIcon atom folder

2023-10-25 15:59 UTC, malexa21 approved these changes

2023-10-25 20:09 UTC, cezarmocanu requested changes
Almost done, only a few improvements remaining

2023-10-25 20:09 UTC, cezarmocanu commented on src/components/atoms/UserIcon/UserIcon.module.css
> +    padding: 10px 4px;
The styling does not match the desing. I would suggest the following improvements

```css
/*For setting size*/
width: 50px;
height: 50px;
padding: 8px;
/*For centering the content inside the box*/
display: flex;
justify-content: center;
align-items: center;
```

2023-10-28 17:31 UTC, malexa21 approved these changes

2023-10-31 06:50 UTC, CezarMocanu-aily approved these changes

2023-10-31 06:50 UTC, cezarmocanu approved these changes

2023-10-31 06:51 UTC, merged